export const UPDATE_VIEWPORT_DIMENSIONS = 'UPDATE_VIEWPORT_DIMENSIONS',
  GET_OS_INFO = 'GET_OS_INFO',
  GET_ENGINE_INFO = 'GET_ENGINE_INFO',
  GET_MOBILE_INFO = 'GET_MOBILE_INFO',
  GET_BROWSER_INFO = 'GET_BROWSER_INFO';
